# Generated by Django 3.2.8 on 2021-10-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naturescall", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restroom",
            old_name="Accessible",
            new_name="accessible",
        ),
        migrations.RenameField(
            model_name="restroom",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="restroom",
            old_name="FamilyFriendly",
            new_name="family_friendly",
        ),
        migrations.RenameField(
            model_name="restroom",
            old_name="Last_Modified",
            new_name="last_modified",
        ),
        migrations.RemoveField(
            model_name="restroom",
            name="TransactionRequired",
        ),
        migrations.RemoveField(
            model_name="restroom",
            name="rating",
        ),
        migrations.AddField(
            model_name="restroom",
            name="transaction_not_required",
            field=models.BooleanField(default=False),
        ),
    ]
