# Generated by Django 3.2.7 on 2021-10-16 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('naturescall', '0003_auto_20211015_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroom',
            name='Description',
            field=models.TextField(default='enter restroom description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restroom',
            name='Last_Modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
