# Generated by Django 3.2.7 on 2021-10-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturescall', '0003_auto_20211015_1716'),
        ('naturescall', '0003_auto_20211016_0420'),
    ]

    operations = [
    ]
