# Generated by Django 3.2.7 on 2021-10-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("naturescall", "0004_auto_20211016_2042"),
        ("naturescall", "0004_merge_0003_auto_20211015_1716_0003_auto_20211016_0420"),
    ]

    operations = []
