# Generated by Django 3.2.9 on 2021-11-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturescall', '0002_restroom_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restroom',
            old_name='subtitle',
            new_name='Subtitle',
        ),
    ]
